using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

[InitializeOnLoad]
public static class NHBasicAlienAssetGenerator
{
    private const string BasePath = "Assets/Art/Enemies/1-1";
    private const string AnimationsPath = BasePath + "/Animations";
    private const string AnimatorPath = BasePath + "/Animator";
    private const string PrefabsPath = BasePath + "/Prefabs";
    private const string MarkerPath = "ProjectSettings/NH_BasicAlien.generated";

    static NHBasicAlienAssetGenerator()
    {
        EditorApplication.delayCall += GenerateIfNeeded;
    }

    [MenuItem("NYAON_HUNTER/Generate NH Basic Alien Assets")]
    public static void Generate()
    {
        AssetDatabase.Refresh();

        Directory.CreateDirectory(AnimationsPath);
        Directory.CreateDirectory(AnimatorPath);
        Directory.CreateDirectory(PrefabsPath);

        ImportSprites();

        AnimationClip move = CreateSpriteClip("Move", "NH_BasicAlien_Move.anim", 10f, true, 14);
        AnimationClip death = CreateSpriteClip("Death", "NH_BasicAlien_Death.anim", 10f, false, 14);

        AnimatorController controller = CreateAnimatorController(move, death);
        CreatePrefab(controller);

        File.WriteAllText(MarkerPath, "Generated by NHBasicAlienAssetGenerator.");
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        Debug.Log("Generated NH_BasicAlien animation clips, Animator Controller, and prefab.");
    }

    private static void GenerateIfNeeded()
    {
        if (!Directory.Exists(BasePath) || File.Exists(MarkerPath))
            return;

        Generate();
    }

    private static void ImportSprites()
    {
        foreach (string path in Directory.GetFiles(BasePath, "*.png", SearchOption.AllDirectories))
        {
            string assetPath = path.Replace('\\', '/');
            TextureImporter importer = AssetImporter.GetAtPath(assetPath) as TextureImporter;
            if (importer == null)
                continue;

            importer.textureType = TextureImporterType.Sprite;
            importer.spriteImportMode = SpriteImportMode.Single;
            importer.alphaIsTransparency = true;
            importer.mipmapEnabled = false;
            importer.textureCompression = TextureImporterCompression.Uncompressed;
            importer.maxTextureSize = 4096;
            importer.filterMode = FilterMode.Bilinear;
            importer.SaveAndReimport();
        }
    }

    private static AnimationClip CreateSpriteClip(string folderName, string clipName, float fps, bool loop, int maxFrames)
    {
        string clipPath = AnimationsPath + "/" + clipName;
        AnimationClip clip = AssetDatabase.LoadAssetAtPath<AnimationClip>(clipPath);
        if (clip == null)
        {
            clip = new AnimationClip();
            AssetDatabase.CreateAsset(clip, clipPath);
        }

        clip.frameRate = fps;

        Sprite[] sprites = Directory.GetFiles(BasePath + "/" + folderName, "*.png", SearchOption.TopDirectoryOnly)
            .OrderBy(path => path)
            .Take(maxFrames)
            .Select(path => AssetDatabase.LoadAssetAtPath<Sprite>(path.Replace('\\', '/')))
            .Where(sprite => sprite != null)
            .ToArray();

        ObjectReferenceKeyframe[] keyframes = new ObjectReferenceKeyframe[sprites.Length];
        for (int i = 0; i < sprites.Length; i++)
        {
            keyframes[i] = new ObjectReferenceKeyframe
            {
                time = i / fps,
                value = sprites[i]
            };
        }

        EditorCurveBinding binding = new EditorCurveBinding
        {
            type = typeof(SpriteRenderer),
            path = string.Empty,
            propertyName = "m_Sprite"
        };

        AnimationUtility.SetObjectReferenceCurve(clip, binding, keyframes);

        AnimationClipSettings settings = AnimationUtility.GetAnimationClipSettings(clip);
        settings.loopTime = loop;
        AnimationUtility.SetAnimationClipSettings(clip, settings);
        EditorUtility.SetDirty(clip);

        return clip;
    }

    private static AnimatorController CreateAnimatorController(AnimationClip move, AnimationClip death)
    {
        string controllerPath = AnimatorPath + "/NH_BasicAlien.controller";
        AnimatorController controller = AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);
        if (controller != null)
            AssetDatabase.DeleteAsset(controllerPath);

        controller = AnimatorController.CreateAnimatorControllerAtPath(controllerPath);
        controller.AddParameter("Dead", AnimatorControllerParameterType.Bool);

        AnimatorStateMachine stateMachine = controller.layers[0].stateMachine;
        stateMachine.states = new ChildAnimatorState[0];
        stateMachine.anyStateTransitions = new AnimatorStateTransition[0];
        stateMachine.entryTransitions = new AnimatorTransition[0];

        AnimatorState moveState = stateMachine.AddState("Move");
        AnimatorState deathState = stateMachine.AddState("Death");

        moveState.motion = move;
        deathState.motion = death;
        stateMachine.defaultState = moveState;

        AnimatorStateTransition deathTransition = stateMachine.AddAnyStateTransition(deathState);
        deathTransition.hasExitTime = false;
        deathTransition.duration = 0f;
        deathTransition.canTransitionToSelf = false;
        deathTransition.AddCondition(AnimatorConditionMode.If, 0f, "Dead");

        EditorUtility.SetDirty(controller);
        return controller;
    }

    private static void CreatePrefab(RuntimeAnimatorController controller)
    {
        GameObject root = new GameObject("NH_BasicAlien");
        SpriteRenderer renderer = root.AddComponent<SpriteRenderer>();
        renderer.sprite = LoadFirstSprite("Move");
        renderer.sortingOrder = 0;

        Animator animator = root.AddComponent<Animator>();
        animator.runtimeAnimatorController = controller;

        Sprite shadowSprite = LoadFirstSprite("Shadow");
        if (shadowSprite != null)
        {
            GameObject shadow = new GameObject("Shadow");
            shadow.transform.SetParent(root.transform, false);
            shadow.transform.localPosition = Vector3.zero;
            SpriteRenderer shadowRenderer = shadow.AddComponent<SpriteRenderer>();
            shadowRenderer.sprite = shadowSprite;
            shadowRenderer.sortingOrder = -1;
        }

        PrefabUtility.SaveAsPrefabAsset(root, PrefabsPath + "/NH_BasicAlien.prefab");
        Object.DestroyImmediate(root);
    }

    private static Sprite LoadFirstSprite(string folderName)
    {
        string path = Directory.GetFiles(BasePath + "/" + folderName, "*.png", SearchOption.TopDirectoryOnly)
            .OrderBy(file => file)
            .FirstOrDefault();

        return string.IsNullOrEmpty(path)
            ? null
            : AssetDatabase.LoadAssetAtPath<Sprite>(path.Replace('\\', '/'));
    }
}
